version: '3'
services:
  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    volumes:
      /var/run/docker.sock:/var/run/docker.sock
  hello:
    image: hello_node
    ports: 
      - 3000:3000